### ISSUE TITLE
Create video stream application class

### ISSUE THREAD

**Issue by dragonprevost** [uvic-aero/onboard-computer#14]
If you look into the `apps/` Directory you will be able to a set of folders, each of which represents an application in the OBC framework. Timelapse, PiCam, TelemData etc. are all examples of applications that run in OBC. To resolve this issue we must create a new application in OBC by duplicating the structure of an already existing application then naming it something relevant to streaming video(Stream, VideoStream, LiveFeed etc...). 

## Notes
* Applications are imported by obc.py when they are being run. Checkout singleton patterns in python to get a better idea of how this application will run in the big picture.
* As of now there is a server providing an http interface for all the applications, this will most likely change this year so don't worry about the routes  aspect of applications
* The streaming application will be a complex class, dont worry about implementing features yet. This issue is only here to get a skeleton of a basic class.

**Comment by joshuacwnewton** [comment]
Out of curiosity, what's the distinction between this VideoStream class and the existing VideoDisplay class? Or, is the intention that this issue will be combined with the "Delete VideoDisplay app" issue with the end result being roughly the same structure?

**Comment by noahwc** [comment]
This will likely be for a future issue but this library https://github.com/jeffbass/imagezmq seems to be promising for video streaming over a network. It works well with OpenCV too.

**Comment by dragonprevost** [comment]
> Out of curiosity, what's the distinction between this VideoStream class and the existing VideoDisplay class? Or, is the intention that this issue will be combined with the "Delete VideoDisplay app" issue with the end result being roughly the same structure?
The video display application would send frames captured on the PiCamera to a video out port on the raspberry pi. This was useful because we had an FPV transmitter that could broadcast the video. This year we will need to use networking protocols to broadcast the live video.... Good question
