### ISSUE TITLE
Create a socket in video server application

### ISSUE THREAD

**Issue by dragonprevost** [uvic-aero/onboard-computer#24]
The first step in getting the video server running is to [create a socket](https://docs.python.org/3.4/howto/sockets.html#creating-a-socket) for clients to connect to. To resolve this issue we must initialize the socket from within the video serving application. It makes the most sense to do this in the `__init__` function of the application so that we are certain the socket is running as soon the application is initialized.

There are examples of socket usage within the [workshops ](https://github.com/uvic-aero/workshops/blob/master/video-stream/server.py) repository. For now we can structure the socket very similarly to the socket in that example.

#### Notes:
* It may be a good idea to get familiar with some networking protocols
  * [tcp](https://en.wikipedia.org/wiki/Transmission_Control_Protocol)
  * [udp](https://en.wikipedia.org/wiki/User_Datagram_Protocol)
  * Try to understand the difference between these two protocols

**Comment by robertbegna** [comment]
hey i'd like to work on this
