### ISSUE TITLE
Create Connections Data Structure for Video Server

### ISSUE THREAD

**Issue by dragonprevost** [uvic-aero/onboard-computer#25]
When serving frames from the OBC picamera, we may have multiple clients that are trying to acquire these frames. In order to accomodate this the VideoServer application has to have a data structure that holds the information for each client so it it can iterate through each client when sending frames

Psuedo Code
```python
# New Connections
data, address = sock.recvfrom(4)
data = data.decode('utf-8')
    if(data == "get"):
        connections.append(address)
```
```python
# Sending Frames
for client in connections:
    sock.sendto(frame_buffer, client)
```

#### Notes:
* This issue 'sort of' depends on #24, communicate with whoever is working on that issue before starting
* Everytime a new client connects you must add this client to the datastructure
* Frames should be pushed to every client in the structure. 
* If a client is not connected anymore it should be removed from the structure

**Comment by noahwc** [comment]
I've begun work on this in the `connections` branch. The basic data structure is there. Next task is to listen for incoming heartbeats from clients.
