### ISSUE TITLE
Create Send Serial Function

### ISSUE THREAD

**Issue by dragonprevost** [uvic-aero/onboard-computer#50]
__Input__: 
```
{
180: [True, False],
break: [True, Flase],
dir1: [0,1],
vel1: [0-255]
dir2: [0,1],
vel2: [0-255]
}
```
1. Convert the input into string structure `<id(int) 180(0,1) break(0,1) dir1(0,1), vel1(0-255), dir2(0,1), vel2(0-255) >`

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kylestang** [comment]
Merged to master
