### ISSUE TITLE
Check Serial Response

### ISSUE THREAD

**Issue by dragonprevost** [uvic-aero/onboard-computer#56]
The serial module is looking great. Before we merge the branch into master I would just like to confirm that the arduino is actually receiving the correct message with no errors. As of now there is a [repository](https://github.com/uvic-aero/radio-test/blob/master/ard-pi_tx-rx.ino) with the arduino program. Checkout this program and quickly review how it works. The main concept is that the arduino sends a confirmation back over the same serial port that it received a message on. The python GroundControl module should receive the message from the arduino and print it off to confirm that it is the expected response.

__Todo__:
* Upload the provided arduino program to the arduino
* Run the GroundControl module and confirm the response is as expected.

**Comment by kylestang** [comment]
Passed serial tests
